### ISSUE TITLE
Lane's not really wearing the blouse

### ISSUE THREAD

**Issue by jpcompton** [johanberntsson/Craverly-Heights_PunyInform#1]
Just downloaded and poked around. Lane does not seem to actually be wearing the blouse:

<img width="509" alt="Screen Shot 2021-07-08 at 11 14 10 AM" src="https://user-images.githubusercontent.com/51372049/124956707-dccb2780-dfdd-11eb-9284-89d3349a8705.png">

**Comment by johanberntsson** [comment]
Thanks. I'd forgotten the transparent attribute. Fixed and updated.
